# Generated by Django 4.2.7 on 2023-12-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default='2'),
            preserve_default=False,
        ),
    ]
